"""First migration

Revision ID: 0b4a7b29fff4
Revises: 
Create Date: 2020-11-14 02:35:25.092783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b4a7b29fff4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction',
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('text')
    )
    op.drop_table('tweets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
    sa.Column('target', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('prediction')
    # ### end Alembic commands ###
